### PR TITLE
during use ffmpeg to push stream to server, occur this error.

### PR DESCRIPTION
**Pull request by bailb**
'Could not write header for output file #0 ...'

    c->s OPTIONS rtsp://localhost:8554/mystream RTSP/1.0
    CSeq: 1
    User-Agent: Lavf58.76.100

    s->c RTSP/1.0 200 OK
    CSeq: 1
    Public: OPTIONS,DESCRIBE,ANNOUNCE,SETUP,PLAY,PAUSE,TEARDOWN,GET_PARAMETER,SET_PARAMETER,REDIRECT,RECORD

    ANNOUNCE rtsp://localhost:8554/mystream RTSP/1.0
    Content-Type: application/sdp
    CSeq: 2
    User-Agent: Lavf58.76.100
    Content-Length: 519

    s->c RTSP/1.0 200 OK
    CSeq: 2

    v=0
    ...
    a=control:streamid=1
    c->s SETUP rtsp://localhost:8554/mystream/streamid=0 RTSP/1.0
    Transport: RTP/AVP/UDP;unicast;client_port=34694-34695;mode=record
    CSeq: 3
    User-Agent: Lavf58.76.100

    RTSP/1.0 200 OK
    CSeq: 3

### CODE REVIEW

**Comment by harlanc** [comment]
@bailb Thanks for you contributions, please help resolve the conflicts..

**Comment by youngday** [comment]
same problem,rtmp work ok,rtsp does not work, same log .
before ffmpeg can push rtsp to xiu,if we can write it in readme.md,so we can check it together

**Comment by bailb** [comment]
&nbsp; &nbsp; I used cmd : "ffmpeg -re -stream_loop -1 &nbsp;-i ./911Mothers_2010W-480p.mp4 -c:v copy &nbsp;-c:a copy &nbsp;-rtsp_transport tcp &nbsp;&nbsp;-f rtsp rtsp://127.0.0.1:5544/live/test" to push the stream to xiu. and used vlc client to play the stream. It's ok for me.
&nbsp;Before, almost can't play the stream. the root cause is that the xiu&nbsp;start to decode the packet without receiving a complete rtsp packet, resulting in the failure to recognize the body in the request.




                       
Original Email
                       
                     

Sender:"young.day"< ***@***.*** &gt;;

Sent Time:2024/3/9 17:47

To:"harlanc/xiu"< ***@***.*** &gt;;

Cc recipient:"bailb"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [harlanc/xiu] during use ffmpeg to push stream to server, occurthis error. (PR #106)




 
same problem,rtmp work ok,rtsp does not work, same log .
 before ffmpeg can push rtsp to xiu,if we can write it in readme.md,so we can check it together

**Comment by harlanc** [comment]
> same problem,rtmp work ok,rtsp does not work, same log . before ffmpeg can push rtsp to xiu,if we can write it in readme.md,so we can check it together

Hi @youngday  does this patch solve your problems?

**Comment by youngday** [comment]
when i use zlmediakit server, it can work,log is below:
```sh
ffmpeg -re -stream_loop -1 -i ./test.mp4 -c:v copy -c:a copy -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:554/live/test
```
```sh
ffmpeg version 5.1.4-0+deb12u1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2016-11-23T22:59:20.000000Z
  Duration: 00:00:16.15, start: 0.000000, bitrate: 4030 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s (default)
    Metadata:
      creation_time   : 2016-11-23T22:59:20.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 4024 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      creation_time   : 2016-11-23T22:59:20.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
Output #0, rtsp, to 'rtsp://127.0.0.1:554/live/test':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    encoder         : Lavf59.27.100
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 4024 kb/s, 29.97 fps, 29.97 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2016-11-23T22:59:20.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s (default)
    Metadata:
      creation_time   : 2016-11-23T22:59:20.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1884 fps= 30 q=-1.0 Lsize=N/A time=00:01:03.85 bitrate=N/A speed=   1x   
```
but when i use xiu server at port 5544, it not work,log is blew:
```sh
ffmpeg -re -stream_loop -1 -i ./test.mp4 -c:v copy -c:a copy -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:5544/live/test
```
```sh
ffmpeg version 5.1.4-0+deb12u1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2016-11-23T22:59:20.000000Z
  Duration: 00:00:16.15, start: 0.000000, bitrate: 4030 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s (default)
    Metadata:
      creation_time   : 2016-11-23T22:59:20.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 4024 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      creation_time   : 2016-11-23T22:59:20.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
Could not write header for output file #0 (incorrect codec parameters ?): Invalid data found when processing input
Error initializing output stream 0:1 --                                                                                                                      
Stream mapping:                                                                                                                                              
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
    Last message repeated 1 times
```

**Comment by youngday** [comment]
i run in three way: 1, cargo install ,and  run xiu;2, your master branch;last,bailb's fork.
os: debian 12, x64.
all not ok.

**Comment by harlanc** [comment]
@youngday add my WeChat for further communications..  harlancc

**Comment by youngday** [comment]
test at version 0.12.5, rtsp working normally,thanks!

**Pull request merged**
